name: "Export and Deploy to GitHub Pages"
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  export_game:
    runs-on: ubuntu-latest
    name: Export Game
    # This runs the build inside a container that already has Godot 3.5.3 ready to go
    container:
      image: barichello/godot-ci:3.5.3
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Create Configuration Presets
        run: |
          mkdir -p build/web
          echo -e '[preset.0]\nname="Web"\nplatform="HTML5"\nrunnable=true\nexport_filter="all_resources"\nexport_path="build/web/index.html"\n[preset.0.options]' > export_presets.cfg

      - name: Compile HTML5 Build
        run: |
          godot -v --headless --export "Web" build/web/index.html

      - name: Deploy Build to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/web
          branch: gh-pages
